### ISSUE TITLE
Your code does not work with google Collection 1.0RC1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NickstaDB/reflections#16]
```
What steps will reproduce the problem?
1. Use Current version of google Collections
2. Use the example code (reduces to the simple annotion)
3. run

What is the expected output? What do you see instead?
none - got the Message:
Exception in thread "DatagramHandlerThread" java.lang.NoSuchMethodError: 
com.google.common.collect.Iterators.forEnumeration(Ljava/util/
Enumeration;)Ljava/util/Iterator;
    at org.reflections.util.VirtualFile$JarFileIterator.<init>
(VirtualFile.java:154)
    at org.reflections.util.VirtualFile$4.iterator(VirtualFile.java:97)
    at org.reflections.util.VirtualFile$5.transform
(VirtualFile.java:169)
    at org.reflections.util.VirtualFile$5.transform
(VirtualFile.java:167)
    at org.reflections.util.FluentIterable$3.transform
(FluentIterable.java:43)
    at org.reflections.util.FluentIterable$3.transform
(FluentIterable.java:41)
    at org.reflections.util.FluentIterable$ForkIterator.computeNext
(FluentIterable.java:81)
    at com.google.common.collect.AbstractIterator.tryToComputeNext
(AbstractIterator.java:135)
    at com.google.common.collect.AbstractIterator.hasNext
(AbstractIterator.java:130)
    at org.reflections.util.FluentIterable$FilterIterator.computeNext
(FluentIterable.java:102)
    at com.google.common.collect.AbstractIterator.tryToComputeNext
(AbstractIterator.java:135)
    at com.google.common.collect.AbstractIterator.hasNext
(AbstractIterator.java:130)
    at org.reflections.util.FluentIterable
$TransformIterator.computeNext(FluentIterable.java:124)
    at com.google.common.collect.AbstractIterator.tryToComputeNext
(AbstractIterator.java:135)
    at com.google.common.collect.AbstractIterator.hasNext
(AbstractIterator.java:130)
    at org.reflections.Reflections.scan(Reflections.java:69)
    at org.reflections.Reflections.<init>(Reflections.java:47)


What version of the product are you using? On what operating system?
I'am running 0.9.2 on gentoo linux using sun jd 1.6.0.13


Please provide any additional information below.
Sorry, there is nothing more i can tell.

```

Original issue reported on code.google.com by `etreu...@googlemail.com` on 24 Apr 2009 at 7:09

**Comment by GoogleCodeExporter** [comment]
```
Here's a diff to make it compile at least, not sure about the failing test 
though 
(was failing before my changes as well).

Index: pom.xml
===================================================================
--- pom.xml (revision 23)
+++ pom.xml (working copy)
@@ -13,15 +13,21 @@
    <name>Reflections</name>
    <description>Reflections - a Java runtime metadata analysis</description>
    <url>http://code.google.com/p/reflections/</url>
-
+   
    <dependencies>
        <dependency>
            <groupId>com.google.collections</groupId>
            <artifactId>google-collections</artifactId>
-           <version>0.9</version>
+           <version>1.0-rc1</version>
        </dependency>
-
+       
        <dependency>
+           <groupId>com.google.code.findbugs</groupId>
+           <artifactId>jsr305</artifactId>
+           <version>1.3.8</version>
+       </dependency>
+       
+       <dependency>
            <groupId>javassist</groupId>
            <artifactId>javassist</artifactId>
            <version>3.8.1.GA</version>
Index: src/main/java/org/reflections/Reflections.java
===================================================================
--- src/main/java/org/reflections/Reflections.java  (revision 23)
+++ src/main/java/org/reflections/Reflections.java  (working copy)
@@ -1,7 +1,7 @@
 package org.reflections;

 import com.google.common.collect.ImmutableSet;
-import static com.google.common.collect.Iterables.newArray;
+import static com.google.common.collect.Iterables.toArray;
 import com.google.common.collect.Sets;
 import com.thoughtworks.xstream.XStream;
 import jsr166y.forkjoin.Ops;
@@ -165,7 +165,7 @@
    public Set<Method> getMethodsAnnotatedWith(Class<? extends Annotation> 
annotation) {
        Collection<String> annotatedWith = 
store.get(MethodAnnotationsScanner.indexName).get(annotation.getName());
        if (annotatedWith != null) {
-           ParallelArray<String> parallelArray = 
ParallelArray.createFromCopy(newArray(annotatedWith, String.class), 
forkJoinPool);
+           ParallelArray<String> parallelArray = 
ParallelArray.createFromCopy(toArray(annotatedWith, String.class), 
forkJoinPool);
            return ImmutableSet.of(parallelArray.withMapping(new 
Ops.Mapper<String, Method>() {
                public Method map(String annotated) {
                    return getMethodFromString(annotated);
@@ -207,7 +207,7 @@
    public Set<Field> getFieldsAnnotatedWith(Class<? extends Annotation> 
annotation) {
        Collection<String> annotatedWith = 
store.get(FieldAnnotationsScanner.indexName).get(annotation.getName());
        if (annotatedWith != null) {
-           ParallelArray<String> parallelArray = 
ParallelArray.createFromCopy(newArray(annotatedWith, String.class), 
forkJoinPool);
+           ParallelArray<String> parallelArray = 
ParallelArray.createFromCopy(toArray(annotatedWith, String.class), 
forkJoinPool);
            return ImmutableSet.of(parallelArray.withMapping(new 
Ops.Mapper<String, Field>() {
                public Field map(String annotated) {
                    return getFieldFromString(annotated);
Index: src/main/java/org/reflections/scanners/ClassAnnotationsScanner.java
===================================================================
--- 
src/main/java/org/reflections/scanners/ClassAnnotationsScanner.java (revision 
23)
+++ 
src/main/java/org/reflections/scanners/ClassAnnotationsScanner.java (working 
copy)
@@ -6,7 +6,7 @@

 import java.util.List;

-import static com.google.common.collect.Iterables.newArray;
+import static com.google.common.collect.Iterables.toArray;

 /**
  *
@@ -20,7 +20,7 @@
     public void scan(final Object cls) {
        final String className = getMetadataAdapter().getClassName(cls);
        List<String> annotationTypes = 
getMetadataAdapter().getClassAnnotationNames(cls);
-       ParallelArray.createFromCopy(newArray(annotationTypes, String.class), 
forkJoinPool).apply(new Ops.Procedure<String>() {
+       ParallelArray.createFromCopy(toArray(annotationTypes, String.class), 
forkJoinPool).apply(new Ops.Procedure<String>() {
            public void apply(String annotationType) {
                if (accept(annotationType)) {
                    populate(annotationType, className);
Index: src/main/java/org/reflections/scanners/FieldAnnotationsScanner.java
===================================================================
--- 
src/main/java/org/reflections/scanners/FieldAnnotationsScanner.java (revision 
23)
+++ 
src/main/java/org/reflections/scanners/FieldAnnotationsScanner.java (working 
copy)
@@ -1,6 +1,6 @@
 package org.reflections.scanners;

-import static com.google.common.collect.Iterables.newArray;
+import static com.google.common.collect.Iterables.toArray;
 import jsr166y.forkjoin.ForkJoinPool;
 import jsr166y.forkjoin.Ops;
 import jsr166y.forkjoin.ParallelArray;
@@ -22,7 +22,7 @@
        List<Object> fields = getMetadataAdapter().getFields(cls);
        for (final Object field : fields) {
            List<String> fieldAnnotations = 
getMetadataAdapter().getFieldAnnotationNames(field);
-           ParallelArray.createFromCopy(newArray(fieldAnnotations, 
String.class), forkJoinPool).apply(new Ops.Procedure<String>() {
+           ParallelArray.createFromCopy(toArray(fieldAnnotations, 
String.class), forkJoinPool).apply(new Ops.Procedure<String>() {
                public void apply(String fieldAnnotation) {
                    if (accept(fieldAnnotation)) {
                        String fieldName = 
getMetadataAdapter().getFieldName(field);
Index: src/main/java/org/reflections/Store.java
===================================================================
--- src/main/java/org/reflections/Store.java    (revision 23)
+++ src/main/java/org/reflections/Store.java    (working copy)
@@ -1,14 +1,19 @@
 package org.reflections;

+import java.util.Collection;
+import java.util.Map;
+import java.util.Set;
+import java.util.concurrent.ConcurrentHashMap;
+
+import javax.annotation.Nullable;
+
 import com.google.common.base.Function;
-import com.google.common.base.Nullable;
 import com.google.common.base.Supplier;
-import com.google.common.collect.*;
+import com.google.common.collect.MapMaker;
+import com.google.common.collect.Multimap;
+import com.google.common.collect.Multimaps;
+import com.google.common.collect.Sets;

-import java.util.Map;
-import java.util.Set;
-import java.util.Collection;
-
 /**
  *
  */
@@ -18,7 +23,7 @@
        public Multimap<String, String> apply(@Nullable String indexName) {
            return Multimaps.newSetMultimap(new MapMaker().<String, 
Collection<String>>makeMap(), new Supplier<Set<String>>() {
                public Set<String> get() {
-                   return Sets.newConcurrentHashSet();
+                   return Sets.newSetFromMap(new 
ConcurrentHashMap<String, Boolean>());
                }
            });
        }




```

Original comment by `brattb...@gmail.com` on 4 May 2009 at 3:23

Attachments:
- [issue-16.diff](https://storage.googleapis.com/google-code-attachments/reflections/issue-16/comment-1/issue-16.diff)

**Comment by GoogleCodeExporter** [comment]
Original comment by `ronm...@gmail.com` on 13 Aug 2009 at 5:27
- Changed state: **Fixed**
